apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "powerdns-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "powerdns-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "powerdns-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "powerdns-operator.labels" . | nindent 8 }}
        app.kubernetes.io/component: controller
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.dnsConfig }}
      dnsConfig: {{ toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity | default .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints | default .Values.global.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      {{- if and (.enabled) (gt (keys . | len) 1) }}
      securityContext:
        {{- include "powerdns-operator.renderSecurityContext" (dict "securityContext" . "context" $) | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "powerdns-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
      - name: {{ .Chart.Name }}
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:{{ .Values.metrics.service.port }}
        {{- if .Values.api.url }}
        - --pdns-api-url={{ .Values.api.url }}
        {{- end }}
        {{- if .Values.api.vhost }}
        - --pdns-api-vhost={{ .Values.api.vhost }}
        {{- end }}
        {{- if .Values.api.timeoutSeconds }}
        - --pdns-api-timeout={{ .Values.api.timeoutSeconds }}
        {{- end }}
        {{- if or .Values.api.tls.caCert .Values.api.tls.existingConfigMap }}
        - --pdns-api-ca-path=/certs/{{ .Values.api.tls.configMapKey }}
        {{- end }}
        {{- if .Values.api.tls.insecure }}
        - --pdns-api-insecure
        {{- end }}
        ports:
        - containerPort: {{ .Values.metrics.service.port }}
          protocol: TCP
          name: http-metrics
        command:
        - /manager
        {{- if or (.Values.credentials.existingSecret) (.Values.credentials.name) }}
        envFrom:
        {{- if .Values.credentials.existingSecret }}
        - secretRef:
            name: {{ .Values.credentials.existingSecret }}
        {{- else if .Values.credentials.name }}
        - secretRef:
            name: {{ .Values.credentials.name }}
        {{- end }}
        {{- end }}
        image: {{ include "powerdns-operator.image" . | trim }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
        {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
        {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        {{- if and (.enabled) (gt (keys . | len) 1) }}
        securityContext:
          {{- include "powerdns-operator.renderSecurityContext" (dict "securityContext" . "context" $) | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if or .Values.api.tls.caCert .Values.api.tls.existingConfigMap }}
        volumeMounts:
        - name: ca-cert
          mountPath: /certs
          readOnly: true
        {{- end }}
      {{- if or .Values.api.tls.caCert .Values.api.tls.existingConfigMap }}
      volumes:
      - name: ca-cert
        configMap:
          {{- if .Values.api.tls.existingConfigMap }}
          name: {{ .Values.api.tls.existingConfigMap }}
          {{- else }}
          name: {{ include "powerdns-operator.fullname" . }}-ca-cert
          {{- end }}
          items:
          - key: {{ .Values.api.tls.configMapKey }}
            path: {{ .Values.api.tls.configMapKey }}
      {{- end }}